Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

1 Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [16]:
import numpy as np

2 Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение.

In [11]:
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7])
a = a.reshape((2, 5))
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

3 Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.

In [14]:
print(a.mean(axis=0))

# a = a.transpose()
# m1 = np.mean(a[0])
# m2 = np.mean(a[1])

# print (m1, m2)


[ 2.   8.4]


4 Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [15]:
mean_a = np.array(a.mean(axis=0))
mean_a 

array([ 2. ,  8.4])

Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [17]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 

In [42]:
a_centered_sp  = a_centered[:, 0]*a_centered[:, 1]
a_centered_sp


array([ 2.4, -0. ,  2.6,  1.6,  1.4])

Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [44]:
print('Результат деления a_centered_sp на N-1, где N - число наблюдений = ',  a_centered_sp/(a.shape[0]-1))

Результат деления a_centered_sp на N-1, где N - число наблюдений =  [ 0.6  -0.    0.65  0.4   0.35]


Проделаем это для всех годов выборки (a_centered_sp) и возьмем среднюю величину, она и будет выборочной ковариацией.

In [49]:
v_cov_a_centered_sp = a_centered_sp.sum()/(a.shape[0]-1)
print(v_cov_a_centered_sp)

2.0


Число, которое мы получили в конце задания 3 является ковариацией двух признаков, ”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [50]:
print(np.cov(a.transpose()))

[[ 1.   2. ]
 [ 2.   4.3]]
